project:
  type: book
  output-dir: docs

book:
  title: "Python for Data Analysis Book Club"
  subtitle: "The R4DS Online Learning Community"
  site-url: https://wesmckinney.com/book/
  repo-url: https://github.com/r4ds/bookclub-py4da
  sharing: [twitter, facebook, linkedin]
  page-footer:
    right: "1850 depiction of Ptilocercus lowii"

  chapters:
    - index.qmd
    - part: 01_main.qmd
      chapters:
        - 01_notes.ipynb
        - 01_video.qmd
    - part: 02_main.qmd
      chapters:
        - 02_video.qmd
    - part: 03_main.qmd
      chapters:
        - 03_notes.qmd
        - 03_video.qmd
    - part: 04_main.qmd
      chapters:
        - 04_video.qmd
    - part: 05_main.qmd
      chapters:
        - 05_notes.qmd
        - 05_video.qmd
    - part: 06_main.qmd
      chapters:
        - 06_notes.qmd
        - 06_video.qmd
    - part: 07_main.qmd
      chapters:
        - 07_video.qmd
    - part: 08_main.qmd
      chapters:
        - 08_video.qmd
    - part: 09_main.qmd
      chapters:
        - 09_video.qmd
    - part: 10_main.qmd
      chapters:
        - 10_video.qmd
    - part: 11_main.qmd
      chapters:
        - 11_video.qmd
    - part: 12_main.qmd
      chapters:
        - 12_notes.ipynb
        - 12_video.qmd
    - part: 13_main.qmd
      chapters:
        - 13_video.qmd
    - part: examples.md
      chapters:
        - example_quarto.qmd
        - example_python.ipynb
  appendices:
    - how-to.qmd

format:
  html:
    theme: cosmo
    fontsize: 16pt

execute:
  freeze: true
